baseURL = "https://digitaltwin.shef.ac.uk/"
languageCode = "en-us"
title = "Digital Twin Research @Sheffield"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logoDT3.png"

# meta data
author = "Digital Twin Research @Sheffield Team"
description = "Digital Twins Sheffield brings together academics and industry focused on digital twin technology in the North of England."

weight = 2
languageCode = "en-gb"
title = "Example site multi-language"
dateFormat = "2 January, 2006"
home = "Home"
menufixed = false

footerDescription = "Digital Twins Sheffield brings together academics and industry focused on digital twin technology in the North of England."
#footerServiceTitle = "Projects"
#footerQuicklinkTitle = "Quicklinks"
#footerAboutTitle = "About"
#footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Digital Twin Research @Sheffield"
description = "Welcome to the Digital Twin Research Hub, bringing together research teams at the Advanced Manufacturing Research Centre and University of Sheffield working on digital twin related research for high-value engineering applications."
button  = false
btnText = "Our Projects"
btnURL  = "about"
videoThumb = ""
videoURL   = ""
bannerImage = "images/banner_wide.jpg"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Our Vision"
description = "We believe that digital twin technology will be a key part of the solutions for; green energy (e.g. via advanced asset management of offshore wind farms); healthcare (e.g. via personalised medicine); smart cities (e.g. by smart management of energy consumption); more efficient manufacturing (e.g. by reducing costs and increasing time efficiency) to name just a few key applications. The Digital Twin Research@Sheffield brings together key research teams to deliver this vision. "

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = false
topTitle= "Useful Links"
title   = "Other Information."
subtitle= "Information related to digital twins"

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "GET IN TOUCH"
title   = "Contact Us."
subtitle= "For more information please complete the form below."
address = "Sir Frederick Mappin Building, Mappin Street, Sheffield"
#phone   = "xxxxx"
#fax     = "xxxx"
facebook= "https://www.facebook.com/theuniversityofsheffield"
twitter = "https://twitter.com/sheffielduni"
#linkedin= "https://www.linkedin.com/"
dribbble= "https://dribbble.com/"
#instagram= "https://www.instagram.com/"
mapLatitude = "51.507351"
mapLongitude= "-0.127758"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Please contact us for more information."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "projects"
url     = "projects"
weight  = 3
[[menu.nav]]
name    = "papers"
url     = "papers"
weight  = 3
[[menu.nav]]
name    = "team"
url     = "team"
weight  = 4
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 5

# Footer Service Menu
#[[menu.service]]
#name    = "graphicdesign"
#url     = "service"
#weight  = 1
#[[menu.service]]
#name    = "webdesign"
#url     = "service"
#weight  = 2
#[[menu.service]]
#name    = "webdevelopment"
#url     = "service"
#weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "About"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "Information"
url     = "information"
weight  = 2
[[menu.quicklink]]
name    = "Projects"
url     = "projects"
weight  = 3
[[menu.quicklink]]
name    = "Contact"
url     = "contact"
weight  = 4
